name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install clang-format
      - uses: actions/checkout@v2
      - uses: mymindstorm/setup-emsdk@v6
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build-wasm
      - run: npm run build-ts
      - run: npm test
      - name: check code style
        run: |
          npm run lint-cpp && npm run lint && [[ $(git status --porcelain | tee /dev/stderr | wc -l) -eq 0 ]]
