name: build
on:
  push:
  pull_request:
permissions: {}
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      EM_VERSION: "3.1.51"
      EM_CACHE_FOLDER: emsdk-cache
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends clang-format-15
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ${{env.EM_CACHE_FOLDER}}
          key: ${{env.EM_VERSION}}
      - uses: mymindstorm/setup-emsdk@v13
        with:
          version: ${{env.EM_VERSION}}
          actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack pnpm install
      - run: corepack pnpm build-wasm
      - run: corepack pnpm build-ts
      - run: corepack pnpm test
      - name: Check code style
        run: |
          corepack pnpm lint
          corepack pnpm clang-format
          corepack pnpm shfmt
          git diff --exit-code
    timeout-minutes: 30
